### ISSUE TITLE
Node Module version out of synch with official Node.JS distribution

### ISSUE THREAD

**Issue by mike-lischke** [electron/node#20]
The current node module version used in this repo is 49 (as of commit electron/node@3ce8afa), however the current module version of the latest Node.JS package is 48 (https://nodejs.org/en/download/releases/), which makes it impossible to build native modules for use in applications that check for the node module version (e.g. Visual Studio Code).

Please reconsider your decision to allow deviating from the version of the official Node.JS distribution.

**Comment by addaleax** [comment]
fwiw, [here](https://github.com/electron/electron/issues/5851#issuecomment-246920775) is a schedule of Node module versions for electron, and Node v7 will come out using a module version of 51, so at least they will align up again soon.

**Comment by MarshallOfSound** [comment]
> which makes it impossible to build native modules for use in applications that check for the node module version (e.g. Visual Studio Code).

I'm not sure what you mean by this, building native modules for electron is thoughouly documented in the Electron repo: https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by mike-lischke** [comment]
I see, standard node-gyp builds might not work. I only wish the tutorial would also address Windows. I'll give that a try and will close this issue once I confirmed that the native module works using that approach. Thanks.

**Comment by MarshallOfSound** [comment]
> I see, standard node-gyp builds might not work.

No, they do not.  This is because Electron's V8 version is linked to Chromium's V8 version rather than Node's.  You would always need to recompile with the correct headers.

**Comment by mike-lischke** [comment]
Ok, that's all been my fault. If the docs say compile with electron-gyp then do it :-) Works fine for me now. Thanks for great product!
