### ISSUE TITLE
fs.realpath.native and fs.realpathSync.native unavailable in electron 3 beta2

### ISSUE THREAD

**Issue by jdalton** [electron/node#44]
The `fs.realpath.native` and `fs.realpathSync.native` have existed since Node 9.2.0+ but I noticed they are unavailable in Electron.

**Comment by codebytere** [comment]
will take a look at this soon!

**Comment by ryzokuken** [comment]
@jdalton It's right here: https://github.com/electron/node/blob/electron-node-v10.2.0/lib/fs.js#L1929-L1937

Could you elaborate what you mean when you say "unavailable in Electron"? Did you try calling them and get an error?

**Comment by jdalton** [comment]
I see they are in the source but if you run code and try to access them they aren't there (at least not for me, I haven't tried beta 3)

**Comment by codebytere** [comment]
ok cool, i'll run some repros this afternoon and try to dig into what this problem may be :)

**Comment by jdalton** [comment]
Found it! 

It's related to the [`fs` method wrappers](https://github.com/electron/electron/issues/13826) that Electron does. 

Related https://github.com/electron/electron/issues/13826

**Comment by codebytere** [comment]
i'll look into refactoring this code to address both these issues!

**Comment by codebytere** [comment]
@jdalton a PR is in progress linked above!

**Comment by jdalton** [comment]
Thank you @codebytere!
